# Generated by Django 3.2.11 on 2022-06-26 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='profile',
        #     name='user',
        # ),
        # migrations.AlterField(
        #     model_name='profile',
        #     name='id',
        #     field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AlterField(
        #     model_name='profile',
        #     name='prof_pic',
        #     field=models.ImageField(blank=True, null=True, upload_to='images/prof_pics'),
        # ),
    ]
