# Generated by Django 3.2.11 on 2022-06-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_auto_20220626_1707'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='profile',
        #     old_name='id',
        #     new_name='user',
        # ),
    ]
