# Generated by Django 3.2.11 on 2022-06-26 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_auto_20220626_1712'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='profile',
        #     name='id_id',
        #     field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
    ]
