# Generated by Django 3.2.11 on 2022-06-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_profile_id'),
    ]

    operations = [

    ]
