# Generated by Django 3.2.11 on 2022-06-27 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogApp', '0010_alter_profiles_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='blog_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
