# Generated by Django 4.0.6 on 2022-07-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0015_alter_posts_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='user',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
